version: '3.8'

services:
  backend:
    container_name: agendai
    build: .
    ports:
      - "${PORT}:${PORT}"  # Express na porta 3333
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}

  postgres:
    container_name: agendai-db
    image: postgres:14
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"  # PostgreSQL exposto corretamente
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
